[TOC]

# 项目中遇到的问题
使用了`useGet`、`usePost`的情况下，一些页面出现了内存泄漏的情况。报错大概是这样的：

```js
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Demo2 (at JestDemo/index.js:11)
```

目前情况麻烦在这个内存泄漏的报错很难复现，场景是这样的：刚开始的时候快速切换页面大概十次有一次会出现一次报错【切换成`slow 3G`报错概率会变高】，然后几次报错之后后续无论怎么操作都不会有相同报错出现，很奇怪。【我估计后端可能做了缓存】

首先我认为应该要复现`bug`，
1. 放弃业务接口，自己写1个接口【模拟一个延迟返回，这样方便取消】
1. 只写一个接口，排除多余因素干扰
1. 只写一个卸载的功能，排除多余因素干扰

另外，我们需要整理下问题出现的场景：
1. 跟接口相关
2. 跟`post`接口相关

基于此我判断应该是`usePost`相关代码某部分出现了问题，接下来的需要通过测试获取数据，然后进行进一步分析和推测。

## UI界面测试
```jsx
import React, { useEffect, useState } from 'react';
import { Swipe } from "../../components";
import { usePost } from "../../utils/hook";

const option = ['demo1','demo2']
export default function JestDemo(props) {
    const [value,setValue] = useState(1);
    return  <div>
        <Swipe option={option} initValue={value} onClick={setValue}/>
        {value === 0 && <Demo1/>}
        {value === 1 && <Demo2/>}
    </div>
};

function Demo1(){
    return <div>
        Demo1
    </div>
}

function Demo2(){
    const {doFetch} = usePost();

    useEffect(()=>{
        doFetch(`http://192.168.2.195:8011/user/login`,{});
    },[doFetch])

    return <div>
        Demo2
    </div>
}
```
这个接口我设了一个3s的延迟，刷新页面后，立刻切换到`Demo1`，3s之后会发现报错。

## `usePost`源码
```js
export function usePost(url, params) {
  const [status, setStatus] = useState({ data: null, loading: true, error: null })
  const pre = useRef(status)
  const cancel_ref = useRef(API.cancelTokenSource())
  const update = useCallback(
    (url, params) => {
      const token = _.get(cancel_ref, 'current.token')
      const s = pre.current
      if (!s.loading) setStatus({ data: s.data, loading: true, error: s.error })
      API.post(url, params, token)
        .then((res) => {
          setStatus({ data: res.data, loading: false, error: null })
        })
        .catch((err) => {
          console.error(err)
          setStatus({ data: null, loading: false, error: err })
        })
    },
    [pre]
  )

  useEffect(() => {
    pre.current = status
  }, [status])

  useEffect(() => {
    if (_.isString(url)) update(url, params)
    return () => {
      if (cancel_ref.current) {
        cancel_ref.current.cancel()
        cancel_ref.current = null
      }
    }
  }, [url, params, update])

  return { ...status, doFetch: update }
}
```
直接说结果，问题出在`API.post(url, params, token)`这一行。【中间其实还有一些其他推测，不过都一一验证排除了】

追踪下`API`这个实例。

## `API`源码 
`API`是对`axios`的一个二次封装，见`rootnet-core/base/task.js`文件。
```js
class API{
  ...省略代码
  
  post(url, params, onUploadProgress, cancel) {
        return this.request('post', url, params, onUploadProgress, cancel);
    }

  ...省略代码
}
```
关键就在参数，这里将参数传错了，以至于底层没有正确的拿到`cancel`进行取消。

顺便说一下`onUploadProgress`，这是源码的接口定义。
```ts
export interface AxiosRequestConfig {
  ...
  onUploadProgress?: (progressEvent: any) => void;
  ...
}
```
`onUploadProgress` 是用于处理上传的进度事件

## 修复并验证
关键行改为`API.post(url, params,undefined,token)`，进行验证，报错消失，问题修复。

同样对`useApi`进行了处理。